/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package promec.software;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.ArrayList;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import static promec.software.visual_Cliente.getConnection;

/**
 *
 * @author ALEX
 */
public class ing_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form ing_Usuario
     */
    Persona user;
    Conexion conexion01; 


    public ing_Usuario() {
        setResizable(false);
        initComponents();
        user = new Persona();
        this.setTitle("ProMec Software");
        conexion01 = new Conexion("promec_Soft");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPantalla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        textApellido = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        textCorreo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        textNumero = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        textUser = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        textContra = new javax.swing.JTextField();
        btnRegi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPantalla.setBackground(new java.awt.Color(255, 255, 255));
        mainPantalla.setFont(new java.awt.Font("Expletus Sans", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Expletus Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 142, 234));
        jLabel1.setText("Bienvenido a ProMec Software");

        textNombre.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        textNombre.setForeground(new java.awt.Color(153, 153, 153));
        textNombre.setText("Ingrese su nombre");
        textNombre.setToolTipText("");
        textNombre.setBorder(null);
        textNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textNombreMousePressed(evt);
            }
        });
        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 142, 234));
        jSeparator1.setPreferredSize(new java.awt.Dimension(150, 40));

        textApellido.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        textApellido.setForeground(new java.awt.Color(153, 153, 153));
        textApellido.setText("Ingrese su apellido");
        textApellido.setToolTipText("");
        textApellido.setBorder(null);
        textApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textApellidoMousePressed(evt);
            }
        });
        textApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textApellidoActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 142, 234));
        jSeparator2.setPreferredSize(new java.awt.Dimension(150, 40));

        textCorreo.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        textCorreo.setForeground(new java.awt.Color(153, 153, 153));
        textCorreo.setText("Correo electronico");
        textCorreo.setToolTipText("");
        textCorreo.setBorder(null);
        textCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textCorreoMousePressed(evt);
            }
        });
        textCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCorreoActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 142, 234));
        jSeparator3.setPreferredSize(new java.awt.Dimension(150, 40));

        textNumero.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        textNumero.setForeground(new java.awt.Color(153, 153, 153));
        textNumero.setText("Numero celular");
        textNumero.setToolTipText("");
        textNumero.setBorder(null);
        textNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textNumeroMousePressed(evt);
            }
        });
        textNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumeroActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 142, 234));
        jSeparator4.setPreferredSize(new java.awt.Dimension(150, 40));

        textUser.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        textUser.setForeground(new java.awt.Color(153, 153, 153));
        textUser.setText("Usuario (No mayor a 10 caracteres)");
        textUser.setToolTipText("");
        textUser.setBorder(null);
        textUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textUserMousePressed(evt);
            }
        });
        textUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUserActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 142, 234));
        jSeparator5.setPreferredSize(new java.awt.Dimension(150, 40));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 142, 234));
        jSeparator6.setPreferredSize(new java.awt.Dimension(150, 40));

        textContra.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        textContra.setForeground(new java.awt.Color(153, 153, 153));
        textContra.setText("Contrasena (No mayor a 10 caracteres)");
        textContra.setToolTipText("");
        textContra.setBorder(null);
        textContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textContraMousePressed(evt);
            }
        });
        textContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContraActionPerformed(evt);
            }
        });

        btnRegi.setBackground(new java.awt.Color(0, 142, 234));
        btnRegi.setFont(new java.awt.Font("Expletus Sans", 1, 18)); // NOI18N
        btnRegi.setForeground(new java.awt.Color(255, 255, 255));
        btnRegi.setText("Registrarse");
        btnRegi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegiMousePressed(evt);
            }
        });
        btnRegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPantallaLayout = new javax.swing.GroupLayout(mainPantalla);
        mainPantalla.setLayout(mainPantallaLayout);
        mainPantallaLayout.setHorizontalGroup(
            mainPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPantallaLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(mainPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPantallaLayout.createSequentialGroup()
                        .addGroup(mainPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addComponent(textNombre, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(mainPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textCorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addComponent(textApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))))
                    .addComponent(textUser)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textContra))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPantallaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        mainPantallaLayout.setVerticalGroup(
            mainPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPantallaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(mainPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPantallaLayout.createSequentialGroup()
                        .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPantallaLayout.createSequentialGroup()
                        .addComponent(textApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(mainPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPantallaLayout.createSequentialGroup()
                        .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPantallaLayout.createSequentialGroup()
                        .addComponent(textNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(textUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textContra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(mainPantalla, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public static Connection getConnection() throws Exception{
        try{
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://localhost:3306/promec_Soft";
            String username = "root";
            String password = "";
            Class.forName(driver);
            
            Connection conn = DriverManager.getConnection(url,username,password);
            System.out.println("Conexión exitosa a base de datos");
            return conn;
        } catch(Exception e){System.out.println(e);}
        return null;
    }
    
    private void btnRegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegiActionPerformed
        user.setNombre(textNombre.getText());
        user.setApellido(textApellido.getText());
        user.setTelefono(textNumero.getText());
 
        if (!user.setEmail(textCorreo.getText())) {
            JOptionPane.showMessageDialog(null, "El correo debe incluir @ y no tener espacios");
        }
        else if (!user.setNuUsuario(textUser.getText())) {
            JOptionPane.showMessageDialog(null, "Usuario o Contrasena no valida");
        }else if(!user.setClave(textContra.getText())){
            JOptionPane.showMessageDialog(null, "Usuario o Contrasena no valida");
        }else if(user.Validacion(textUser.getText(), textContra.getText())){
            JOptionPane.showMessageDialog(null, "Los datos ingresados son correctos");
            JOptionPane.showMessageDialog(null, "Redirigendo a inicio de sesión");
            
            
            
            inicio_Sesion page_Sesion = new inicio_Sesion();
            page_Sesion.setSize(720, 472);
            page_Sesion.setLocation(0,0);

            mainPantalla.removeAll();
            mainPantalla.add(page_Sesion, BorderLayout.CENTER);
            mainPantalla.revalidate();
            mainPantalla.repaint();
            
            try{
            Connection con = getConnection();
        String Cadena = "INSERT INTO registro (nombre, apellido, correo, numero, usuario, password) VALUES ('"+user.getNombre()+"', '"+user.getApellido()+"', '"+user.getEmail()+"', '"+user.getTelefono()+"', '"+user.getNuUsuario()+"', '"+user.getClave()+"');";            
            PreparedStatement posted = con.prepareStatement(Cadena);
            posted.executeUpdate();
            //return true;
        } catch(Exception e){
            System.out.println(e);
            //return false;
        }
            
            
            
        }else {
            JOptionPane.showMessageDialog(null, "No es posible realizar el registro");
        }   
        
        
        
        
        
    }//GEN-LAST:event_btnRegiActionPerformed

    private void textUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUserActionPerformed

    private void textNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumeroActionPerformed

    private void textCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCorreoActionPerformed

    private void textApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textApellidoActionPerformed

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void textNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textNombreMousePressed
        // TODO add your handling code here:
        if (textNombre.getText().equals("Ingrese su nombre")) {
            textNombre.setText("");
            textNombre.setForeground(Color.black);
        }
    }//GEN-LAST:event_textNombreMousePressed

    private void textApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textApellidoMousePressed
       if (textApellido.getText().equals("Ingrese su apellido")) {
            textApellido.setText("");
            textApellido.setForeground(Color.black);
        }
    }//GEN-LAST:event_textApellidoMousePressed

    private void textCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textCorreoMousePressed
        if (textCorreo.getText().equals("Correo electronico")) {
            textCorreo.setText("");
            textCorreo.setForeground(Color.black);
        }
    }//GEN-LAST:event_textCorreoMousePressed

    private void textContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textContraMousePressed
        if (textContra.getText().equals("Contrasena (No mayor a 10 caracteres)")){
            textContra.setText("");
            textContra.setForeground(Color.black);
        }
        if (textUser.getText().isEmpty()){
            textUser.setText("Usuario (No mayor a 10 caracteres)");
            textUser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_textContraMousePressed

    private void textContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textContraActionPerformed

    private void textUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textUserMousePressed
        if (textUser.getText().equals("Usuario (No mayor a 10 caracteres)")){
            textUser.setText("");
            textUser.setForeground(Color.black);
        } 
        if (textContra.getText().isEmpty()){
            textContra.setText("********");
            textContra.setForeground(Color.gray);
        }
 
    }//GEN-LAST:event_textUserMousePressed

    private void textNumeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textNumeroMousePressed
           if (textNumero.getText().equals("Numero celular")) {
               textNumero.setText("");
               textNumero.setForeground(Color.black);
        }
    }//GEN-LAST:event_textNumeroMousePressed

    private void btnRegiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegiMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegiMousePressed

    private void btnRegiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ing_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ing_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ing_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ing_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ing_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel mainPantalla;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textContra;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textNumero;
    private javax.swing.JTextField textUser;
    // End of variables declaration//GEN-END:variables
    
    public boolean infoUser(){
    textUser.getText();
    return true;
    }
    public boolean infoPass(){
    textContra.getText();
    return true;
    }

}
