/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package promec.software;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author ALEX
 */
public class inicio_Sesion extends javax.swing.JPanel {

    /**
     * Creates new form inicio_Sesion
     */
    
    usuario user01;
    ing_Usuario userOG;
    
    public inicio_Sesion() {
        initComponents();
        user01 = new usuario();
        userOG = new ing_Usuario();
        
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainInicio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ini_User = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ini_Pass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        ini_Sesion = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Expletus Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 142, 234));
        jLabel1.setText("Bienvenido a ProMec Software");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(720, 472));
        setLayout(new java.awt.BorderLayout());

        mainInicio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Expletus Sans", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 38, 233));
        jLabel3.setText("Pro Mec Software");

        ini_User.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        ini_User.setForeground(new java.awt.Color(153, 153, 153));
        ini_User.setText("Usuario");
        ini_User.setBorder(null);
        ini_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ini_UserMousePressed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 38, 233));
        jSeparator1.setPreferredSize(new java.awt.Dimension(150, 40));

        ini_Pass.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        ini_Pass.setForeground(new java.awt.Color(153, 153, 153));
        ini_Pass.setText("********");
        ini_Pass.setBorder(null);
        ini_Pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ini_PassMousePressed(evt);
            }
        });
        ini_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ini_PassActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 38, 233));
        jSeparator2.setPreferredSize(new java.awt.Dimension(150, 40));

        ini_Sesion.setBackground(new java.awt.Color(0, 38, 233));
        ini_Sesion.setFont(new java.awt.Font("Expletus Sans", 1, 18)); // NOI18N
        ini_Sesion.setForeground(new java.awt.Color(255, 255, 255));
        ini_Sesion.setText("Iniciar sesión");
        ini_Sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ini_Sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ini_SesionMousePressed(evt);
            }
        });
        ini_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ini_SesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainInicioLayout = new javax.swing.GroupLayout(mainInicio);
        mainInicio.setLayout(mainInicioLayout);
        mainInicioLayout.setHorizontalGroup(
            mainInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainInicioLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel3))
            .addGroup(mainInicioLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(ini_User, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(mainInicioLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(mainInicioLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(ini_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(mainInicioLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(mainInicioLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(ini_Sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainInicioLayout.setVerticalGroup(
            mainInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainInicioLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(70, 70, 70)
                .addComponent(ini_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ini_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ini_Sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(mainInicio, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ini_SesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ini_SesionMousePressed
        /*if (user.setNuUsuario(ini_User.getText().equals(compro.textUser.getText()))) {
        }*/
        //usuario01.Validacion(ini_User.getText(), String.valueOf(ini_Pass.getPassword()));
        
    }//GEN-LAST:event_ini_SesionMousePressed

    private void ini_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ini_SesionActionPerformed
    if (user01.setNuUsuario(String.valueOf(ini_User.getText().equals(userOG.infoUser()))) && 
        user01.setClave(String.valueOf(String.valueOf(ini_Pass.getPassword()).equals(userOG.infoPass())))) {
            JOptionPane.showMessageDialog(null, "Ingreso exitoso");    
            JOptionPane.showMessageDialog(null, "Redirigendo a menu principal");
            
            menu_Principal page_Menu = new menu_Principal();
            page_Menu.setSize(720, 472);
            page_Menu.setLocation(0,0);
            
            mainInicio.removeAll();
            mainInicio.add(page_Menu, BorderLayout.CENTER);
            mainInicio.revalidate();
            mainInicio.repaint();
            
            
        }else {
            JOptionPane.showMessageDialog(null, "Datos incorrectos, ingresar de nuevo");
        }        
    }//GEN-LAST:event_ini_SesionActionPerformed

    
    
    
    
    
    private void ini_UserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ini_UserMousePressed
         if (ini_User.getText().equals("Usuario")){
            ini_User.setText("");
            ini_User.setForeground(Color.black);
        } 
        if (String.valueOf(ini_Pass.getPassword()).isEmpty()){
            ini_Pass.setText("********");
            ini_Pass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ini_UserMousePressed

    private void ini_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ini_PassActionPerformed
        // TODO add your handling code here:
         if (String.valueOf(ini_Pass.getPassword()).equals("********") ){
            ini_Pass.setText("");
            ini_Pass.setForeground(Color.black);
        }
        if (ini_User.getText().isEmpty()) {
            ini_User.setText("Usuario");
            ini_User.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ini_PassActionPerformed

    private void ini_PassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ini_PassMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ini_PassMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ini_Pass;
    private javax.swing.JButton ini_Sesion;
    private javax.swing.JTextField ini_User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainInicio;
    // End of variables declaration//GEN-END:variables
    
}
