/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package promec.software;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author ALEX
 */
public class menu_Principal extends javax.swing.JPanel {

    /**
     * Creates new form menu_Principal
     */
    public menu_Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMenu_Pago = new javax.swing.JButton();
        btnMenu_Cliente = new javax.swing.JButton();
        btnMenu_Servicios = new javax.swing.JButton();
        btnMenu_Almacen = new javax.swing.JButton();
        btnMenu_Salir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(720, 472));
        setLayout(new java.awt.BorderLayout());

        mainMenu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Expletus Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 38, 233));
        jLabel1.setText("Menu Principal");

        btnMenu_Pago.setBackground(new java.awt.Color(0, 38, 233));
        btnMenu_Pago.setFont(new java.awt.Font("Expletus Sans", 1, 18)); // NOI18N
        btnMenu_Pago.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu_Pago.setText("Pagos y Facturas");
        btnMenu_Pago.setFocusable(false);
        btnMenu_Pago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu_Pago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenu_PagoMousePressed(evt);
            }
        });
        btnMenu_Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu_PagoActionPerformed(evt);
            }
        });

        btnMenu_Cliente.setBackground(new java.awt.Color(0, 38, 233));
        btnMenu_Cliente.setFont(new java.awt.Font("Expletus Sans", 1, 18)); // NOI18N
        btnMenu_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu_Cliente.setText("Clientes");
        btnMenu_Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenu_ClienteMousePressed(evt);
            }
        });
        btnMenu_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu_ClienteActionPerformed(evt);
            }
        });

        btnMenu_Servicios.setBackground(new java.awt.Color(0, 38, 233));
        btnMenu_Servicios.setFont(new java.awt.Font("Expletus Sans", 1, 18)); // NOI18N
        btnMenu_Servicios.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu_Servicios.setText("Servicios");
        btnMenu_Servicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu_Servicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenu_ServiciosMousePressed(evt);
            }
        });
        btnMenu_Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu_ServiciosActionPerformed(evt);
            }
        });

        btnMenu_Almacen.setBackground(new java.awt.Color(0, 38, 233));
        btnMenu_Almacen.setFont(new java.awt.Font("Expletus Sans", 1, 18)); // NOI18N
        btnMenu_Almacen.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu_Almacen.setText("Almacen");
        btnMenu_Almacen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu_Almacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenu_AlmacenMousePressed(evt);
            }
        });
        btnMenu_Almacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu_AlmacenActionPerformed(evt);
            }
        });

        btnMenu_Salir.setBackground(new java.awt.Color(0, 38, 233));
        btnMenu_Salir.setFont(new java.awt.Font("Expletus Sans", 1, 18)); // NOI18N
        btnMenu_Salir.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu_Salir.setText("Cerrar Sesión");
        btnMenu_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenu_SalirMousePressed(evt);
            }
        });
        btnMenu_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                        .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMenu_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenu_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenu_Servicios, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenu_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenu_Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(240, 240, 240))))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenu_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu_Servicios, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnMenu_Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(mainMenu, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenu_ClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu_ClienteMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenu_ClienteMousePressed

    private void btnMenu_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu_ClienteActionPerformed
            visual_Cliente page_Cliente = new visual_Cliente();
            page_Cliente.setSize(720, 472);
            page_Cliente.setLocation(0,0);

            mainMenu.removeAll();
            mainMenu.add(page_Cliente, BorderLayout.CENTER);
            mainMenu.revalidate();
            mainMenu.repaint();        
    }//GEN-LAST:event_btnMenu_ClienteActionPerformed

    private void btnMenu_PagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu_PagoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenu_PagoMousePressed

    private void btnMenu_PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu_PagoActionPerformed
            visual_Pago page_Pago = new visual_Pago();
            page_Pago.setSize(720, 472);
            page_Pago.setLocation(0,0);

            mainMenu.removeAll();
            mainMenu.add(page_Pago, BorderLayout.CENTER);
            mainMenu.revalidate();
            mainMenu.repaint();    
        
    }//GEN-LAST:event_btnMenu_PagoActionPerformed

    private void btnMenu_SalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu_SalirMousePressed
        
 
        
    }//GEN-LAST:event_btnMenu_SalirMousePressed

    private void btnMenu_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu_SalirActionPerformed
        // TODO add your handling code here:
            JOptionPane.showMessageDialog(null, "Sesión Exitosa");
            JOptionPane.showMessageDialog(null, "Gracias por usar ProMec Software");
            inicio_Sesion page_Sesion = new inicio_Sesion();
            page_Sesion.setSize(720, 472);
            page_Sesion.setLocation(0,0);

            mainMenu.removeAll();
            mainMenu.add(page_Sesion, BorderLayout.CENTER);
            mainMenu.revalidate();
            mainMenu.repaint();
    }//GEN-LAST:event_btnMenu_SalirActionPerformed

    private void btnMenu_ServiciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu_ServiciosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenu_ServiciosMousePressed

    private void btnMenu_ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu_ServiciosActionPerformed
        // TODO add your handling code here:
         visual_Servicio page_Serv = new visual_Servicio();
            page_Serv.setSize(720, 495);
            page_Serv.setLocation(0,0);

            mainMenu.removeAll();
            mainMenu.add(page_Serv, BorderLayout.CENTER);
            mainMenu.revalidate();
            mainMenu.repaint();   
    }//GEN-LAST:event_btnMenu_ServiciosActionPerformed

    private void btnMenu_AlmacenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu_AlmacenMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenu_AlmacenMousePressed

    private void btnMenu_AlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu_AlmacenActionPerformed
        // TODO add your handling code here:
            visual_Almacen page_Alma = new visual_Almacen();
            page_Alma.setSize(720, 472);
            page_Alma.setLocation(0,0);

            mainMenu.removeAll();
            mainMenu.add(page_Alma, BorderLayout.CENTER);
            mainMenu.revalidate();
            mainMenu.repaint();    
    }//GEN-LAST:event_btnMenu_AlmacenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu_Almacen;
    private javax.swing.JButton btnMenu_Cliente;
    private javax.swing.JButton btnMenu_Pago;
    private javax.swing.JButton btnMenu_Salir;
    private javax.swing.JButton btnMenu_Servicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainMenu;
    // End of variables declaration//GEN-END:variables
}
