/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package promec.software;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import static promec.software.visual_Cliente.getConnection;

/**
 *
 * @author ALEX
 */
public class visual_Servicio extends javax.swing.JPanel {
    
    /**
     * Creates new form visual_Servicio
     */
    Servicio servicio01;
    Tecnico tecnico01;
    Conexion conexion01;

    public visual_Servicio() {
        initComponents();
        p_IngServ.setVisible(false);
        p_EliServ.setVisible(false);
        p_List.setVisible(false);
        
        LabelPlaca.setVisible(false);
        LabelModelo.setVisible(false);
        LabelDesc.setVisible(false);
        LabelNombTec.setVisible(false);
        LabelTel.setVisible(false);
        LabelCorreo.setVisible(false);
        Label_IdTec.setVisible(false);

        verPlacaTxt.setVisible(false);
        verModeloTxt.setVisible(false);
        verDescTxt.setVisible(false);
        ver_NombTecTxt.setVisible(false);
        verTelTxt.setVisible(false);
        verEmailTxt.setVisible(false);
        ver_IdTecTxt.setVisible(false);
        
        servicio01 = new Servicio();
        tecnico01 = new Tecnico();
        conexion01 = new Conexion("promec_Soft");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_Servicio = new javax.swing.JPanel();
        p_Btn = new javax.swing.JPanel();
        ing_ServBtn = new javax.swing.JButton();
        eli_ServBtn = new javax.swing.JButton();
        ver_ListBtn = new javax.swing.JButton();
        volver_MenuPBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        p_IngServ = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        agre_Serv = new javax.swing.JButton();
        placTxt = new javax.swing.JTextField();
        modeloTxt = new javax.swing.JTextField();
        idTxt = new javax.swing.JTextField();
        descTxt = new javax.swing.JTextField();
        telTxt = new javax.swing.JTextField();
        correoTxt = new javax.swing.JTextField();
        nombtecTxt = new javax.swing.JTextField();
        idtecTxt = new javax.swing.JTextField();
        p_EliServ = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        idEliTxt = new javax.swing.JTextField();
        eli_Serv = new javax.swing.JButton();
        p_List = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        idServTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        veriServBtn = new javax.swing.JButton();
        LabelPlaca = new javax.swing.JLabel();
        LabelModelo = new javax.swing.JLabel();
        Label_IdTec = new javax.swing.JLabel();
        LabelCorreo = new javax.swing.JLabel();
        verEmailTxt = new javax.swing.JTextField();
        verTelTxt = new javax.swing.JTextField();
        verModeloTxt = new javax.swing.JTextField();
        verPlacaTxt = new javax.swing.JTextField();
        LabelTel = new javax.swing.JLabel();
        ver_IdTecTxt = new javax.swing.JTextField();
        LabelDesc = new javax.swing.JLabel();
        verDescTxt = new javax.swing.JTextField();
        LabelNombTec = new javax.swing.JLabel();
        ver_NombTecTxt = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        p_Btn.setBackground(new java.awt.Color(0, 142, 234));

        ing_ServBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        ing_ServBtn.setForeground(new java.awt.Color(0, 142, 234));
        ing_ServBtn.setText("Ingresar Servicio");
        ing_ServBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ing_ServBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ing_ServBtnActionPerformed(evt);
            }
        });

        eli_ServBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        eli_ServBtn.setForeground(new java.awt.Color(0, 142, 234));
        eli_ServBtn.setText("Eliminar Servicio");
        eli_ServBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eli_ServBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eli_ServBtnActionPerformed(evt);
            }
        });

        ver_ListBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        ver_ListBtn.setForeground(new java.awt.Color(0, 142, 234));
        ver_ListBtn.setText("Ver Listado");
        ver_ListBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ver_ListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_ListBtnActionPerformed(evt);
            }
        });

        volver_MenuPBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        volver_MenuPBtn.setForeground(new java.awt.Color(0, 142, 234));
        volver_MenuPBtn.setText("Volver a Menú");
        volver_MenuPBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver_MenuPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_MenuPBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Expletus Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Servicios");

        javax.swing.GroupLayout p_BtnLayout = new javax.swing.GroupLayout(p_Btn);
        p_Btn.setLayout(p_BtnLayout);
        p_BtnLayout.setHorizontalGroup(
            p_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_BtnLayout.createSequentialGroup()
                .addGroup(p_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_BtnLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(p_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ing_ServBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eli_ServBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ver_ListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volver_MenuPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p_BtnLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        p_BtnLayout.setVerticalGroup(
            p_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_BtnLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(ing_ServBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eli_ServBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ver_ListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(volver_MenuPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Expletus Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 142, 234));
        jLabel2.setText("Ingresar Servicio");

        jLabel5.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 142, 234));
        jLabel5.setText("Placa");

        jLabel6.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 142, 234));
        jLabel6.setText("Modelo de vehículo");

        jLabel7.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 142, 234));
        jLabel7.setText("ID de servicio");

        jLabel8.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 142, 234));
        jLabel8.setText("Descripción de servicio");

        jLabel9.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 142, 234));
        jLabel9.setText("Teléfono");

        jLabel10.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 142, 234));
        jLabel10.setText("Correo");

        jLabel11.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 142, 234));
        jLabel11.setText("Nombre de técnico");

        jLabel12.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 142, 234));
        jLabel12.setText("ID de Técnico");

        agre_Serv.setBackground(new java.awt.Color(0, 142, 234));
        agre_Serv.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        agre_Serv.setForeground(new java.awt.Color(255, 255, 255));
        agre_Serv.setText("Agregar Servicio");
        agre_Serv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agre_Serv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agre_ServActionPerformed(evt);
            }
        });

        placTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        modeloTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        idTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        descTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        telTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        correoTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        nombtecTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        idtecTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        javax.swing.GroupLayout p_IngServLayout = new javax.swing.GroupLayout(p_IngServ);
        p_IngServ.setLayout(p_IngServLayout);
        p_IngServLayout.setHorizontalGroup(
            p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_IngServLayout.createSequentialGroup()
                .addGroup(p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_IngServLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel2))
                    .addGroup(p_IngServLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_IngServLayout.createSequentialGroup()
                                .addGroup(p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(placTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_IngServLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idtecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_IngServLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nombtecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_IngServLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_IngServLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_IngServLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(p_IngServLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(agre_Serv, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        p_IngServLayout.setVerticalGroup(
            p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_IngServLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(placTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombtecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_IngServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idtecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(agre_Serv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );

        jLabel13.setFont(new java.awt.Font("Expletus Sans", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 142, 234));
        jLabel13.setText("Eliminar Servicio");

        jLabel14.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 142, 234));
        jLabel14.setText("Ingresa ID para proceder");

        idEliTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        eli_Serv.setBackground(new java.awt.Color(0, 142, 234));
        eli_Serv.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        eli_Serv.setForeground(new java.awt.Color(255, 255, 255));
        eli_Serv.setText("Eliminar");
        eli_Serv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eli_Serv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eli_ServActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_EliServLayout = new javax.swing.GroupLayout(p_EliServ);
        p_EliServ.setLayout(p_EliServLayout);
        p_EliServLayout.setHorizontalGroup(
            p_EliServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_EliServLayout.createSequentialGroup()
                .addGroup(p_EliServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_EliServLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel13))
                    .addGroup(p_EliServLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idEliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_EliServLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(eli_Serv, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        p_EliServLayout.setVerticalGroup(
            p_EliServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_EliServLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(p_EliServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idEliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(eli_Serv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(338, 338, 338))
        );

        jLabel15.setFont(new java.awt.Font("Expletus Sans", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 142, 234));
        jLabel15.setText("Listado de Servicios");

        idServTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        idServTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idServTxtActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 142, 234));
        jLabel16.setText("Ingresa ID de Servicio");

        veriServBtn.setBackground(new java.awt.Color(0, 142, 234));
        veriServBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        veriServBtn.setForeground(new java.awt.Color(255, 255, 255));
        veriServBtn.setText("Verificar");
        veriServBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        veriServBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veriServBtnActionPerformed(evt);
            }
        });

        LabelPlaca.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        LabelPlaca.setForeground(new java.awt.Color(0, 142, 234));
        LabelPlaca.setText("Placa");

        LabelModelo.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        LabelModelo.setForeground(new java.awt.Color(0, 142, 234));
        LabelModelo.setText("Modelo de vehículo");

        Label_IdTec.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        Label_IdTec.setForeground(new java.awt.Color(0, 142, 234));
        Label_IdTec.setText("ID Técnico");

        LabelCorreo.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        LabelCorreo.setForeground(new java.awt.Color(0, 142, 234));
        LabelCorreo.setText("Correo");

        verEmailTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        verTelTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        verModeloTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        verPlacaTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        LabelTel.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        LabelTel.setForeground(new java.awt.Color(0, 142, 234));
        LabelTel.setText("Teléfono");

        ver_IdTecTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        LabelDesc.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        LabelDesc.setForeground(new java.awt.Color(0, 142, 234));
        LabelDesc.setText("Descripción");

        verDescTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        LabelNombTec.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        LabelNombTec.setForeground(new java.awt.Color(0, 142, 234));
        LabelNombTec.setText("Nombre Técnico");

        ver_NombTecTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        javax.swing.GroupLayout p_ListLayout = new javax.swing.GroupLayout(p_List);
        p_List.setLayout(p_ListLayout);
        p_ListLayout.setHorizontalGroup(
            p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ListLayout.createSequentialGroup()
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_ListLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel15))
                    .addGroup(p_ListLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_ListLayout.createSequentialGroup()
                                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelPlaca)
                                    .addComponent(LabelModelo)
                                    .addComponent(LabelDesc))
                                .addGap(18, 18, 18)
                                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(verModeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(verPlacaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(verDescTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_ListLayout.createSequentialGroup()
                                    .addComponent(Label_IdTec)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ver_IdTecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_ListLayout.createSequentialGroup()
                                    .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(p_ListLayout.createSequentialGroup()
                                            .addComponent(LabelCorreo)
                                            .addGap(35, 35, 35))
                                        .addComponent(LabelTel, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(81, 81, 81)
                                    .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(verTelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(verEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_ListLayout.createSequentialGroup()
                                    .addComponent(LabelNombTec)
                                    .addGap(43, 43, 43)
                                    .addComponent(ver_NombTecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(p_ListLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(veriServBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idServTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        p_ListLayout.setVerticalGroup(
            p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idServTxt))
                .addGap(18, 18, 18)
                .addComponent(veriServBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(p_ListLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(verPlacaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(verModeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(verDescTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombTec, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(ver_NombTecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verTelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(verEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_IdTec, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(ver_IdTecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout v_ServicioLayout = new javax.swing.GroupLayout(v_Servicio);
        v_Servicio.setLayout(v_ServicioLayout);
        v_ServicioLayout.setHorizontalGroup(
            v_ServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_ServicioLayout.createSequentialGroup()
                .addComponent(p_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_IngServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(v_ServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_ServicioLayout.createSequentialGroup()
                    .addGap(0, 215, Short.MAX_VALUE)
                    .addComponent(p_EliServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(v_ServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_ServicioLayout.createSequentialGroup()
                    .addGap(0, 220, Short.MAX_VALUE)
                    .addComponent(p_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        v_ServicioLayout.setVerticalGroup(
            v_ServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p_IngServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(v_ServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(p_EliServ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(v_ServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(p_List, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(v_Servicio, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ing_ServBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ing_ServBtnActionPerformed
        p_IngServ.setVisible(true);
        p_List.setVisible(false);
        p_EliServ.setVisible(false);
    }//GEN-LAST:event_ing_ServBtnActionPerformed

    private void eli_ServBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eli_ServBtnActionPerformed
        p_IngServ.setVisible(false);
        p_List.setVisible(false);
        p_EliServ.setVisible(true);      
    }//GEN-LAST:event_eli_ServBtnActionPerformed

    private void ver_ListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_ListBtnActionPerformed
             p_IngServ.setVisible(false);
        p_List.setVisible(true);
        p_EliServ.setVisible(false);
    }//GEN-LAST:event_ver_ListBtnActionPerformed

    private void volver_MenuPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_MenuPBtnActionPerformed
        menu_Principal mainMenu = new menu_Principal();
        mainMenu.setSize(720, 472);
        mainMenu.setLocation(0,0);

        v_Servicio.removeAll();
        v_Servicio.add(mainMenu, BorderLayout.CENTER);
        v_Servicio.revalidate();
        v_Servicio.repaint();
    }//GEN-LAST:event_volver_MenuPBtnActionPerformed

    private void agre_ServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agre_ServActionPerformed
         
        servicio01.setPlaca(placTxt.getText());
        servicio01.setModeloCoche(modeloTxt.getText());
        servicio01.setDescripcion(descTxt.getText());
        servicio01.setTelefono(telTxt.getText());
        tecnico01.setNombre(nombtecTxt.getText());
        if (!servicio01.setEmail(correoTxt.getText())) {
            JOptionPane.showMessageDialog(null, "Correo inválido");
        }else if(!servicio01.setIdServicio(idTxt.getText())){
            JOptionPane.showMessageDialog(null, "ID de Servicio inválido");
        }else if(!tecnico01.setId_Tec(idtecTxt.getText())){
            JOptionPane.showMessageDialog(null, "ID de Técnico inválido");
        }else {
               try{
                Connection con = getConnection();
            String Cadena = "INSERT INTO servicios(placa, modelo, id_Serv, desc_Serv, telefono, correo, nombre_Tec, id_Tec) VALUES ('"+servicio01.getPlaca()+"', '"+servicio01.getModeloCoche()+"', '"+servicio01.getIdServicio()+"', '"+servicio01.getDescripcion()+"', '"+servicio01.getTelefono()+"', '"+servicio01.getEmail()+"',  '"+tecnico01.getNombre()+"',  '"+tecnico01.getId_Tec()+"',);";            
                PreparedStatement posted = con.prepareStatement(Cadena);
                posted.executeUpdate();
                //return true;
            } catch(Exception e){
                System.out.println(e);
                //return false;
            }
            JOptionPane.showMessageDialog(null, "Servicio guardado exitosamente");
            
        }
    }//GEN-LAST:event_agre_ServActionPerformed

    private void eli_ServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eli_ServActionPerformed
        if (idEliTxt.getText().equals(idTxt.getText())) {
            LabelPlaca.setVisible(false);
            LabelModelo.setVisible(false);
            LabelDesc.setVisible(false);
            LabelNombTec.setVisible(false);
            LabelTel.setVisible(false);
            LabelCorreo.setVisible(false);
            Label_IdTec.setVisible(false);

            verPlacaTxt.setVisible(false);
            verModeloTxt.setVisible(false);
            verDescTxt.setVisible(false);
            ver_NombTecTxt.setVisible(false);
            verTelTxt.setVisible(false);
            verEmailTxt.setVisible(false);
            ver_IdTecTxt.setVisible(false);
            
            verPlacaTxt.setText("");
            verModeloTxt.setText("");
            verDescTxt.setText("");
            ver_NombTecTxt.setText("");
            verTelTxt.setText("");
            verEmailTxt.setText("");
            ver_IdTecTxt.setText("");
            
            placTxt.setText("");
            modeloTxt.setText("");
            idTxt.setText("");
            descTxt.setText("");
            telTxt.setText("");
            correoTxt.setText("");
            nombtecTxt.setText("");
            idtecTxt.setText("");
            
            
            
            servicio01.setPlaca("");
            servicio01.setModeloCoche("");
            servicio01.setDescripcion("");
            tecnico01.setNombre("");
            servicio01.setIdServicio("");
            servicio01.setTelefono("");
            servicio01.setEmail("");
            tecnico01.setNombre("");        
        
            JOptionPane.showMessageDialog(null, "Servicio eliminado exitosamente");
        }else {
            JOptionPane.showMessageDialog(null, "Favor de proporcionar ID correcto");
            
        }
        
    }//GEN-LAST:event_eli_ServActionPerformed

    private void idServTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idServTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idServTxtActionPerformed

    private void veriServBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veriServBtnActionPerformed
        if (idServTxt.getText().equals(idTxt.getText())) {

            LabelPlaca.setVisible(true);
            LabelModelo.setVisible(true);
            LabelDesc.setVisible(true);
            LabelNombTec.setVisible(true);
            LabelTel.setVisible(true);
            LabelCorreo.setVisible(true);
            Label_IdTec.setVisible(true);

            verPlacaTxt.setVisible(true);
            verModeloTxt.setVisible(true);
            verDescTxt.setVisible(true);
            ver_NombTecTxt.setVisible(true);
            verTelTxt.setVisible(true);
            verEmailTxt.setVisible(true);
            ver_IdTecTxt.setVisible(true);

            
            verPlacaTxt.setText(placTxt.getText());
            verModeloTxt.setText(modeloTxt.getText());
            verDescTxt.setText(descTxt.getText());
            ver_NombTecTxt.setText(nombtecTxt.getText());
            verTelTxt.setText(telTxt.getText());
            verEmailTxt.setText(correoTxt.getText());
            ver_IdTecTxt.setText(idtecTxt.getText());
        }else {
            JOptionPane.showMessageDialog(null, "ID incorrecto, ingresar de nuevo");
        }
    }//GEN-LAST:event_veriServBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCorreo;
    private javax.swing.JLabel LabelDesc;
    private javax.swing.JLabel LabelModelo;
    private javax.swing.JLabel LabelNombTec;
    private javax.swing.JLabel LabelPlaca;
    private javax.swing.JLabel LabelTel;
    private javax.swing.JLabel Label_IdTec;
    private javax.swing.JButton agre_Serv;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JTextField descTxt;
    private javax.swing.JButton eli_Serv;
    private javax.swing.JButton eli_ServBtn;
    private javax.swing.JTextField idEliTxt;
    private javax.swing.JTextField idServTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JTextField idtecTxt;
    private javax.swing.JButton ing_ServBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JTextField nombtecTxt;
    private javax.swing.JPanel p_Btn;
    private javax.swing.JPanel p_EliServ;
    private javax.swing.JPanel p_IngServ;
    private javax.swing.JPanel p_List;
    private javax.swing.JTextField placTxt;
    private javax.swing.JTextField telTxt;
    private javax.swing.JPanel v_Servicio;
    private javax.swing.JTextField verDescTxt;
    private javax.swing.JTextField verEmailTxt;
    private javax.swing.JTextField verModeloTxt;
    private javax.swing.JTextField verPlacaTxt;
    private javax.swing.JTextField verTelTxt;
    private javax.swing.JTextField ver_IdTecTxt;
    private javax.swing.JButton ver_ListBtn;
    private javax.swing.JTextField ver_NombTecTxt;
    private javax.swing.JButton veriServBtn;
    private javax.swing.JButton volver_MenuPBtn;
    // End of variables declaration//GEN-END:variables
}
