/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package promec.software;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;


/**
 *
 * @author ALEX
 */
public class visual_Cliente extends javax.swing.JPanel {

    /**
     * Creates new form visual_Cliente
     */
    Cliente cliente01;
    Conexion conexion01; 
    public visual_Cliente() {
        initComponents();
        p_IngCliente.setVisible(false);
        p_EliCliente.setVisible(false);
        p_List.setVisible(false);
        
        LabelName.setVisible(false);
        LabelPlaca.setVisible(false);
        LabelModelo.setVisible(false);
        LabelTel.setVisible(false);
        LabelCorreo.setVisible(false);

        verNameTxt.setVisible(false);
        verPlacaTxt.setVisible(false);
        verModeloTxt.setVisible(false);
        verTelTxt.setVisible(false);
        verEmailTxt.setVisible(false);
        
        
        conexion01 = new Conexion("promec_Soft");
        cliente01 = new Cliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_Cliente = new javax.swing.JPanel();
        p_Btn = new javax.swing.JPanel();
        ing_ClienteBtn = new javax.swing.JButton();
        eli_ClienteBtn = new javax.swing.JButton();
        ver_CarteraBtn = new javax.swing.JButton();
        volver_MenuPBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        p_IngCliente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        agre_Cliente = new javax.swing.JButton();
        nombreTxt = new javax.swing.JTextField();
        apellidoTxt = new javax.swing.JTextField();
        placTxt = new javax.swing.JTextField();
        modeloTxt = new javax.swing.JTextField();
        telTxt = new javax.swing.JTextField();
        correoTxt = new javax.swing.JTextField();
        idtecTxt = new javax.swing.JTextField();
        p_EliCliente = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        idEliTxt = new javax.swing.JTextField();
        eliminarBtn = new javax.swing.JButton();
        p_List = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        LabelName = new javax.swing.JLabel();
        LabelPlaca = new javax.swing.JLabel();
        LabelModelo = new javax.swing.JLabel();
        LabelTel = new javax.swing.JLabel();
        LabelCorreo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idVeriTxt = new javax.swing.JTextField();
        verNameTxt = new javax.swing.JTextField();
        verPlacaTxt = new javax.swing.JTextField();
        verModeloTxt = new javax.swing.JTextField();
        verTelTxt = new javax.swing.JTextField();
        verEmailTxt = new javax.swing.JTextField();
        check_IdBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        p_Btn.setBackground(new java.awt.Color(0, 142, 234));

        ing_ClienteBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        ing_ClienteBtn.setForeground(new java.awt.Color(0, 142, 234));
        ing_ClienteBtn.setText("Ingresar Cliente");
        ing_ClienteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ing_ClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ing_ClienteBtnActionPerformed(evt);
            }
        });

        eli_ClienteBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        eli_ClienteBtn.setForeground(new java.awt.Color(0, 142, 234));
        eli_ClienteBtn.setText("Eliminar Cliente");
        eli_ClienteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eli_ClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eli_ClienteBtnActionPerformed(evt);
            }
        });

        ver_CarteraBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        ver_CarteraBtn.setForeground(new java.awt.Color(0, 142, 234));
        ver_CarteraBtn.setText("Ver Cartera ");
        ver_CarteraBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ver_CarteraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_CarteraBtnActionPerformed(evt);
            }
        });

        volver_MenuPBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        volver_MenuPBtn.setForeground(new java.awt.Color(0, 142, 234));
        volver_MenuPBtn.setText("Volver a Menú");
        volver_MenuPBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver_MenuPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_MenuPBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Expletus Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clientes");

        javax.swing.GroupLayout p_BtnLayout = new javax.swing.GroupLayout(p_Btn);
        p_Btn.setLayout(p_BtnLayout);
        p_BtnLayout.setHorizontalGroup(
            p_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_BtnLayout.createSequentialGroup()
                .addGroup(p_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_BtnLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(p_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ing_ClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eli_ClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ver_CarteraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volver_MenuPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p_BtnLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        p_BtnLayout.setVerticalGroup(
            p_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_BtnLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(ing_ClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eli_ClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ver_CarteraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(volver_MenuPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Expletus Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 142, 234));
        jLabel2.setText("Ingresar Cliente");

        jLabel3.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 142, 234));
        jLabel3.setText("Nombre de Cliente");

        jLabel4.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 142, 234));
        jLabel4.setText("Apellido de Cliente");

        jLabel5.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 142, 234));
        jLabel5.setText("Placa");

        jLabel6.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 142, 234));
        jLabel6.setText("Modelo de vehículo");

        jLabel9.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 142, 234));
        jLabel9.setText("Teléfono");

        jLabel10.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 142, 234));
        jLabel10.setText("Correo");

        jLabel12.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 142, 234));
        jLabel12.setText("ID de Cliente");

        agre_Cliente.setBackground(new java.awt.Color(0, 142, 234));
        agre_Cliente.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        agre_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        agre_Cliente.setText("Agregar Cliente");
        agre_Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agre_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agre_ClienteActionPerformed(evt);
            }
        });

        nombreTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        apellidoTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        placTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        modeloTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        telTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        correoTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        idtecTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        javax.swing.GroupLayout p_IngClienteLayout = new javax.swing.GroupLayout(p_IngCliente);
        p_IngCliente.setLayout(p_IngClienteLayout);
        p_IngClienteLayout.setHorizontalGroup(
            p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_IngClienteLayout.createSequentialGroup()
                .addGroup(p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_IngClienteLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_IngClienteLayout.createSequentialGroup()
                                .addGroup(p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(placTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(p_IngClienteLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel2))
                            .addGroup(p_IngClienteLayout.createSequentialGroup()
                                .addGroup(p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(65, 65, 65)
                                .addGroup(p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idtecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(p_IngClienteLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(agre_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        p_IngClienteLayout.setVerticalGroup(
            p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_IngClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(placTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(p_IngClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idtecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(agre_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        jLabel13.setFont(new java.awt.Font("Expletus Sans", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 142, 234));
        jLabel13.setText("Eliminar Cliente");

        jLabel14.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 142, 234));
        jLabel14.setText("Ingresa ID para proceder");

        idEliTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        idEliTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEliTxtActionPerformed(evt);
            }
        });

        eliminarBtn.setBackground(new java.awt.Color(0, 142, 234));
        eliminarBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        eliminarBtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarBtn.setText("Eliminar");
        eliminarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_EliClienteLayout = new javax.swing.GroupLayout(p_EliCliente);
        p_EliCliente.setLayout(p_EliClienteLayout);
        p_EliClienteLayout.setHorizontalGroup(
            p_EliClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_EliClienteLayout.createSequentialGroup()
                .addGroup(p_EliClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_EliClienteLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel13))
                    .addGroup(p_EliClienteLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idEliTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_EliClienteLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(eliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        p_EliClienteLayout.setVerticalGroup(
            p_EliClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_EliClienteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(p_EliClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idEliTxt))
                .addGap(18, 18, 18)
                .addComponent(eliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
        );

        jLabel15.setFont(new java.awt.Font("Expletus Sans", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 142, 234));
        jLabel15.setText("Clientes");

        LabelName.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        LabelName.setForeground(new java.awt.Color(0, 142, 234));
        LabelName.setText("Nombre de Cliente");

        LabelPlaca.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        LabelPlaca.setForeground(new java.awt.Color(0, 142, 234));
        LabelPlaca.setText("Placa");

        LabelModelo.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        LabelModelo.setForeground(new java.awt.Color(0, 142, 234));
        LabelModelo.setText("Modelo de vehículo");

        LabelTel.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        LabelTel.setForeground(new java.awt.Color(0, 142, 234));
        LabelTel.setText("Teléfono");

        LabelCorreo.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        LabelCorreo.setForeground(new java.awt.Color(0, 142, 234));
        LabelCorreo.setText("Correo");

        jLabel8.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 142, 234));
        jLabel8.setText("Ingresar ID de cliente:");

        idVeriTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        verNameTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        verPlacaTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        verModeloTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        verTelTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        verEmailTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        check_IdBtn.setBackground(new java.awt.Color(0, 142, 234));
        check_IdBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        check_IdBtn.setForeground(new java.awt.Color(255, 255, 255));
        check_IdBtn.setText("Verificar");
        check_IdBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        check_IdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_IdBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_ListLayout = new javax.swing.GroupLayout(p_List);
        p_List.setLayout(p_ListLayout);
        p_ListLayout.setHorizontalGroup(
            p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ListLayout.createSequentialGroup()
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_ListLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(LabelName)
                            .addComponent(LabelPlaca)
                            .addComponent(LabelModelo)
                            .addComponent(LabelTel)
                            .addComponent(LabelCorreo))
                        .addGap(18, 18, 18)
                        .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verTelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verModeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verPlacaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idVeriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check_IdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p_ListLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel15)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        p_ListLayout.setVerticalGroup(
            p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idVeriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(check_IdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_ListLayout.createSequentialGroup()
                        .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(p_ListLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(verPlacaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(verModeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(verTelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(verEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout v_ClienteLayout = new javax.swing.GroupLayout(v_Cliente);
        v_Cliente.setLayout(v_ClienteLayout);
        v_ClienteLayout.setHorizontalGroup(
            v_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_ClienteLayout.createSequentialGroup()
                .addComponent(p_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_IngCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(v_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_ClienteLayout.createSequentialGroup()
                    .addGap(0, 231, Short.MAX_VALUE)
                    .addComponent(p_EliCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(v_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_ClienteLayout.createSequentialGroup()
                    .addGap(0, 231, Short.MAX_VALUE)
                    .addComponent(p_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        v_ClienteLayout.setVerticalGroup(
            v_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p_IngCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(v_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(v_ClienteLayout.createSequentialGroup()
                    .addComponent(p_EliCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(v_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(v_ClienteLayout.createSequentialGroup()
                    .addComponent(p_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );

        add(v_Cliente, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
     public static Connection getConnection() throws Exception{
        try{
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://localhost:3306/promec_Soft";
            String username = "root";
            String password = "";
            Class.forName(driver);
            
            Connection conn = DriverManager.getConnection(url,username,password);
            System.out.println("Conexión exitosa a base de datos");
            return conn;
        } catch(Exception e){System.out.println(e);}
        
        
        return null;
    }
    
    
    private void ing_ClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ing_ClienteBtnActionPerformed
        p_IngCliente.setVisible(true);
        p_EliCliente.setVisible(false);
        p_List.setVisible(false);
    }//GEN-LAST:event_ing_ClienteBtnActionPerformed

    private void eli_ClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eli_ClienteBtnActionPerformed
        p_IngCliente.setVisible(false);
        p_EliCliente.setVisible(true);
        p_List.setVisible(false);
    }//GEN-LAST:event_eli_ClienteBtnActionPerformed

    private void ver_CarteraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_CarteraBtnActionPerformed
        p_IngCliente.setVisible(false);
        p_EliCliente.setVisible(false);
        p_List.setVisible(true);
    }//GEN-LAST:event_ver_CarteraBtnActionPerformed

    private void volver_MenuPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_MenuPBtnActionPerformed
        menu_Principal mainMenu = new menu_Principal();
        mainMenu.setSize(720, 472);
        mainMenu.setLocation(0,0);

        v_Cliente.removeAll();
        v_Cliente.add(mainMenu, BorderLayout.CENTER);
        v_Cliente.revalidate();
        v_Cliente.repaint();
    }//GEN-LAST:event_volver_MenuPBtnActionPerformed

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        if (idEliTxt.getText().equals(idtecTxt.getText())) {
            
            verNameTxt.setText(" ");
            verModeloTxt.setText(" ");
            verPlacaTxt.setText(" ");
            verTelTxt.setText(" ");
            verEmailTxt.setText(" ");

            nombreTxt.setText(" ");
            apellidoTxt.setText(" ");
            modeloTxt.setText(" ");
            placTxt.setText(" ");
            telTxt.setText(" ");
            correoTxt.setText(" ");
            idtecTxt.setText(" ");
            
            cliente01.setNombre("");
            cliente01.setApellido("");
            cliente01.setModeloCoche("");
            cliente01.setPlaca("");
            cliente01.setTelefono("");
            cliente01.setEmail("");
            cliente01.setId("");
            
            LabelName.setVisible(false);
            LabelPlaca.setVisible(false);
            LabelModelo.setVisible(false);
            LabelTel.setVisible(false);
            LabelCorreo.setVisible(false);

            verNameTxt.setVisible(false);
            verPlacaTxt.setVisible(false);
            verModeloTxt.setVisible(false);
            verTelTxt.setVisible(false);
            verEmailTxt.setVisible(false);
            
            JOptionPane.showMessageDialog(null, "Cliente eliminado exitosamente");
        }else {
            JOptionPane.showMessageDialog(null, "ID incorrecto, ingresar de nuevo");
        }
    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void agre_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agre_ClienteActionPerformed
        cliente01.setTelefono(telTxt.getText());
        if (!cliente01.setNombre(nombreTxt.getText()) ) {
            JOptionPane.showMessageDialog(null, "Favor de agregar Nombre");
        }else if(!cliente01.setApellido(apellidoTxt.getText())){
            JOptionPane.showMessageDialog(null, "Favor de agregar apellido");
        }else if(!cliente01.setPlaca(placTxt.getText())){
            JOptionPane.showMessageDialog(null, "Favor de ingresar placa");
        }else if(!cliente01.setModeloCoche(modeloTxt.getText())){
            JOptionPane.showMessageDialog(null, "Favor de ingresar modelo de coche");
        }else if(!cliente01.setEmail(correoTxt.getText())){
            JOptionPane.showMessageDialog(null, "Correo inválido");
        }else if(!cliente01.setId(idtecTxt.getText())){
            JOptionPane.showMessageDialog(null, "ID  debe contener 5 dígitos");
        }else {
            try{
                Connection con = getConnection();
            String Cadena = "INSERT INTO clientes (nombre, apellido, placa, modelo, telefono, correo, id_Cliente) VALUES ('"+cliente01.getNombre()+"', '"+cliente01.getApellido()+"', '"+cliente01.getPlaca()+"', '"+cliente01.getModeloCoche()+"', '"+cliente01.getTelefono()+"', '"+cliente01.getEmail()+"', '"+cliente01.getId()+"');";            
                PreparedStatement posted = con.prepareStatement(Cadena);
                posted.executeUpdate();
                //return true;
            } catch(Exception e){
                System.out.println(e);
                //return false;
            }
            JOptionPane.showMessageDialog(null, "Cliente guardado exitosamente");
        }
        
        
        
        
        
    }//GEN-LAST:event_agre_ClienteActionPerformed

    private void check_IdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_IdBtnActionPerformed
        if (idVeriTxt.getText().equals(idtecTxt.getText())) {
            LabelName.setVisible(true);
            LabelPlaca.setVisible(true);
            LabelModelo.setVisible(true);
            LabelTel.setVisible(true);
            LabelCorreo.setVisible(true);

            verNameTxt.setVisible(true);
            verPlacaTxt.setVisible(true);
            verModeloTxt.setVisible(true);
            verTelTxt.setVisible(true);
            verEmailTxt.setVisible(true);
            
            verNameTxt.setText(cliente01.getNombre() + " " + cliente01.getApellido());
            verPlacaTxt.setText(cliente01.getPlaca());
            verModeloTxt.setText(cliente01.getModeloCoche());
            verTelTxt.setText(String.valueOf(cliente01.getTelefono()));
            verEmailTxt.setText(cliente01.getEmail());
            
        }else {
            JOptionPane.showMessageDialog(null, "ID incorrecto, ingresar de nuevo");
        }
    }//GEN-LAST:event_check_IdBtnActionPerformed

    private void idEliTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEliTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEliTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCorreo;
    private javax.swing.JLabel LabelModelo;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelPlaca;
    private javax.swing.JLabel LabelTel;
    private javax.swing.JButton agre_Cliente;
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JButton check_IdBtn;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JButton eli_ClienteBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JTextField idEliTxt;
    private javax.swing.JTextField idVeriTxt;
    private javax.swing.JTextField idtecTxt;
    private javax.swing.JButton ing_ClienteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JPanel p_Btn;
    private javax.swing.JPanel p_EliCliente;
    private javax.swing.JPanel p_IngCliente;
    private javax.swing.JPanel p_List;
    private javax.swing.JTextField placTxt;
    private javax.swing.JTextField telTxt;
    private javax.swing.JPanel v_Cliente;
    private javax.swing.JTextField verEmailTxt;
    private javax.swing.JTextField verModeloTxt;
    private javax.swing.JTextField verNameTxt;
    private javax.swing.JTextField verPlacaTxt;
    private javax.swing.JTextField verTelTxt;
    private javax.swing.JButton ver_CarteraBtn;
    private javax.swing.JButton volver_MenuPBtn;
    // End of variables declaration//GEN-END:variables
}
