/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package promec.software;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import static promec.software.visual_Cliente.getConnection;

/**
 *
 * @author ALEX
 */
public class visual_Pago extends javax.swing.JPanel {

    /**
     * Creates new form visual_Pago
     */
    Factura factura01;
    corte_Caja caja;
    Conexion conexion01;

    public visual_Pago() {
        initComponents();
        p_ingFac.setVisible(false);
        p_capIngreso.setVisible(false);
        p_mosFac.setVisible(false);
        p_capEgreso.setVisible(false);
        p_corteCaja.setVisible(false);
        idLabel.setVisible(false);
        
        montoLabel.setVisible(false);
        descLabel.setVisible(false);
        ver_IdFacTxt.setVisible(false);
        ver_MontoTxt.setVisible(false);
        ver_DescTxt.setVisible(false);
    
        conexion01 = new Conexion("promec_Soft");
        factura01 = new Factura();
        caja = new corte_Caja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_Pago = new javax.swing.JPanel();
        p_Btn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        volver_MenuPBtn = new javax.swing.JButton();
        ver_CorteCajaBtn = new javax.swing.JButton();
        add_EgresoBtn = new javax.swing.JButton();
        add_IngresoBtn = new javax.swing.JButton();
        ver_FacturaBtn = new javax.swing.JButton();
        ing_FacturaBtn = new javax.swing.JButton();
        p_ingFac = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        montoTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        descTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        salvar_Fac = new javax.swing.JButton();
        p_capIngreso = new javax.swing.JPanel();
        salvar_Ing = new javax.swing.JButton();
        ingresoTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        p_mosFac = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        veri_IdTxt = new javax.swing.JTextField();
        ver_Fac = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        montoLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        ver_IdFacTxt = new javax.swing.JTextField();
        ver_MontoTxt = new javax.swing.JTextField();
        ver_DescTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        p_capEgreso = new javax.swing.JPanel();
        salvar_Egr = new javax.swing.JButton();
        egresoTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        p_corteCaja = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        verIngTxt = new javax.swing.JTextField();
        verEgrTxt = new javax.swing.JTextField();
        verCorte = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        v_Pago.setBackground(new java.awt.Color(204, 204, 204));

        p_Btn.setBackground(new java.awt.Color(0, 142, 234));

        jLabel1.setFont(new java.awt.Font("Expletus Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pagos y Facturas");

        volver_MenuPBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        volver_MenuPBtn.setForeground(new java.awt.Color(0, 142, 234));
        volver_MenuPBtn.setText("Volver a Menú");
        volver_MenuPBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver_MenuPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_MenuPBtnActionPerformed(evt);
            }
        });

        ver_CorteCajaBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        ver_CorteCajaBtn.setForeground(new java.awt.Color(0, 142, 234));
        ver_CorteCajaBtn.setText("Corte Caja");
        ver_CorteCajaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ver_CorteCajaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_CorteCajaBtnActionPerformed(evt);
            }
        });

        add_EgresoBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        add_EgresoBtn.setForeground(new java.awt.Color(0, 142, 234));
        add_EgresoBtn.setText("Agregar Egreso");
        add_EgresoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_EgresoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_EgresoBtnActionPerformed(evt);
            }
        });

        add_IngresoBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        add_IngresoBtn.setForeground(new java.awt.Color(0, 142, 234));
        add_IngresoBtn.setText("Agregar Ingreso");
        add_IngresoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_IngresoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_IngresoBtnActionPerformed(evt);
            }
        });

        ver_FacturaBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        ver_FacturaBtn.setForeground(new java.awt.Color(0, 142, 234));
        ver_FacturaBtn.setText("Mostrar Factura");
        ver_FacturaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ver_FacturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_FacturaBtnActionPerformed(evt);
            }
        });

        ing_FacturaBtn.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        ing_FacturaBtn.setForeground(new java.awt.Color(0, 142, 234));
        ing_FacturaBtn.setText("Ingresar Factura");
        ing_FacturaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ing_FacturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ing_FacturaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_BtnLayout = new javax.swing.GroupLayout(p_Btn);
        p_Btn.setLayout(p_BtnLayout);
        p_BtnLayout.setHorizontalGroup(
            p_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_BtnLayout.createSequentialGroup()
                .addGroup(p_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_BtnLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(p_BtnLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(p_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ing_FacturaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ver_FacturaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_IngresoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_EgresoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ver_CorteCajaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volver_MenuPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        p_BtnLayout.setVerticalGroup(
            p_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_BtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(ing_FacturaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ver_FacturaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(add_IngresoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(add_EgresoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ver_CorteCajaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(volver_MenuPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jLabel2.setFont(new java.awt.Font("Expletus Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 142, 234));
        jLabel2.setText("Ingresar Factura");

        jLabel3.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 142, 234));
        jLabel3.setText("Ingresar monto");

        montoTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        montoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoTxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 142, 234));
        jLabel5.setText("Descripción");

        descTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 142, 234));
        jLabel6.setText("ID Factura");

        idTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });

        salvar_Fac.setBackground(new java.awt.Color(0, 142, 234));
        salvar_Fac.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        salvar_Fac.setForeground(new java.awt.Color(255, 255, 255));
        salvar_Fac.setText("Agregar Factura");
        salvar_Fac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salvar_Fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_FacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_ingFacLayout = new javax.swing.GroupLayout(p_ingFac);
        p_ingFac.setLayout(p_ingFacLayout);
        p_ingFacLayout.setHorizontalGroup(
            p_ingFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ingFacLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(p_ingFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(p_ingFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(montoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(p_ingFacLayout.createSequentialGroup()
                .addGroup(p_ingFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_ingFacLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2))
                    .addGroup(p_ingFacLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(salvar_Fac, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_ingFacLayout.setVerticalGroup(
            p_ingFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ingFacLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(p_ingFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(montoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_ingFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_ingFacLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_ingFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(salvar_Fac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        salvar_Ing.setBackground(new java.awt.Color(0, 142, 234));
        salvar_Ing.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        salvar_Ing.setForeground(new java.awt.Color(255, 255, 255));
        salvar_Ing.setText("Guardar Ingreso");
        salvar_Ing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salvar_Ing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_IngActionPerformed(evt);
            }
        });

        ingresoTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        ingresoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoTxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Expletus Sans", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 142, 234));
        jLabel4.setText("Capturar Ingreso");

        jLabel9.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 142, 234));
        jLabel9.setText("Monto en caja");

        javax.swing.GroupLayout p_capIngresoLayout = new javax.swing.GroupLayout(p_capIngreso);
        p_capIngreso.setLayout(p_capIngresoLayout);
        p_capIngresoLayout.setHorizontalGroup(
            p_capIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_capIngresoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(ingresoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(p_capIngresoLayout.createSequentialGroup()
                .addGroup(p_capIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_capIngresoLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel4))
                    .addGroup(p_capIngresoLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(salvar_Ing, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_capIngresoLayout.setVerticalGroup(
            p_capIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_capIngresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addGroup(p_capIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingresoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(salvar_Ing, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 142, 234));
        jLabel7.setText("ID de Factura");

        veri_IdTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        veri_IdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veri_IdTxtActionPerformed(evt);
            }
        });

        ver_Fac.setBackground(new java.awt.Color(0, 142, 234));
        ver_Fac.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        ver_Fac.setForeground(new java.awt.Color(255, 255, 255));
        ver_Fac.setText("Ver Factura");
        ver_Fac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ver_Fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_FacActionPerformed(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        idLabel.setForeground(new java.awt.Color(0, 142, 234));
        idLabel.setText("ID de Factura");

        montoLabel.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        montoLabel.setForeground(new java.awt.Color(0, 142, 234));
        montoLabel.setText("Monto");

        descLabel.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        descLabel.setForeground(new java.awt.Color(0, 142, 234));
        descLabel.setText("Descripción");

        ver_IdFacTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        ver_IdFacTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_IdFacTxtActionPerformed(evt);
            }
        });

        ver_MontoTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        ver_MontoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_MontoTxtActionPerformed(evt);
            }
        });

        ver_DescTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        ver_DescTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_DescTxtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Expletus Sans", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 142, 234));
        jLabel10.setText("Mostrar Factura");

        javax.swing.GroupLayout p_mosFacLayout = new javax.swing.GroupLayout(p_mosFac);
        p_mosFac.setLayout(p_mosFacLayout);
        p_mosFacLayout.setHorizontalGroup(
            p_mosFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mosFacLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(p_mosFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_mosFacLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(veri_IdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_mosFacLayout.createSequentialGroup()
                        .addGroup(p_mosFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descLabel)
                            .addComponent(montoLabel)
                            .addComponent(idLabel))
                        .addGap(18, 18, 18)
                        .addGroup(p_mosFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ver_DescTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ver_MontoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ver_IdFacTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_mosFacLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ver_Fac, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(p_mosFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_mosFacLayout.createSequentialGroup()
                    .addContainerGap(191, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(130, 130, 130)))
        );
        p_mosFacLayout.setVerticalGroup(
            p_mosFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_mosFacLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(p_mosFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(veri_IdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(ver_Fac, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(p_mosFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addGroup(p_mosFacLayout.createSequentialGroup()
                        .addComponent(ver_IdFacTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(p_mosFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ver_MontoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(montoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(p_mosFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ver_DescTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descLabel))))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(p_mosFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_mosFacLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel10)
                    .addContainerGap(413, Short.MAX_VALUE)))
        );

        salvar_Egr.setBackground(new java.awt.Color(0, 142, 234));
        salvar_Egr.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        salvar_Egr.setForeground(new java.awt.Color(255, 255, 255));
        salvar_Egr.setText("Guardar Egreso");
        salvar_Egr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salvar_Egr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_EgrActionPerformed(evt);
            }
        });

        egresoTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Expletus Sans", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 142, 234));
        jLabel8.setText("Capturar Egreso");

        jLabel11.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 142, 234));
        jLabel11.setText("Egreso en caja");

        javax.swing.GroupLayout p_capEgresoLayout = new javax.swing.GroupLayout(p_capEgreso);
        p_capEgreso.setLayout(p_capEgresoLayout);
        p_capEgresoLayout.setHorizontalGroup(
            p_capEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_capEgresoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(egresoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(p_capEgresoLayout.createSequentialGroup()
                .addGroup(p_capEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_capEgresoLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel8))
                    .addGroup(p_capEgresoLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(salvar_Egr, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_capEgresoLayout.setVerticalGroup(
            p_capEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_capEgresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(36, 36, 36)
                .addGroup(p_capEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(egresoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(salvar_Egr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 142, 234));
        jLabel12.setText("Ingresos en caja: ");

        jLabel13.setFont(new java.awt.Font("Expletus Sans", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 142, 234));
        jLabel13.setText("Corte de Caja");

        jLabel14.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 142, 234));
        jLabel14.setText("Saldo al corte:");

        jLabel15.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 142, 234));
        jLabel15.setText("Egresos en caja:");

        verIngTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        verIngTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verIngTxtActionPerformed(evt);
            }
        });

        verEgrTxt.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        verEgrTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEgrTxtActionPerformed(evt);
            }
        });

        verCorte.setFont(new java.awt.Font("Expletus Sans", 1, 16)); // NOI18N
        verCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCorteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_corteCajaLayout = new javax.swing.GroupLayout(p_corteCaja);
        p_corteCaja.setLayout(p_corteCajaLayout);
        p_corteCajaLayout.setHorizontalGroup(
            p_corteCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_corteCajaLayout.createSequentialGroup()
                .addGroup(p_corteCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_corteCajaLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel13))
                    .addGroup(p_corteCajaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(p_corteCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_corteCajaLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verIngTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_corteCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(p_corteCajaLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(verCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_corteCajaLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(18, 18, 18)
                                    .addComponent(verEgrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        p_corteCajaLayout.setVerticalGroup(
            p_corteCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_corteCajaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addGap(35, 35, 35)
                .addGroup(p_corteCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verIngTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(p_corteCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verEgrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(p_corteCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE))
                .addGap(237, 237, 237))
        );

        javax.swing.GroupLayout v_PagoLayout = new javax.swing.GroupLayout(v_Pago);
        v_Pago.setLayout(v_PagoLayout);
        v_PagoLayout.setHorizontalGroup(
            v_PagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_PagoLayout.createSequentialGroup()
                .addComponent(p_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_ingFac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(v_PagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_PagoLayout.createSequentialGroup()
                    .addContainerGap(222, Short.MAX_VALUE)
                    .addComponent(p_capIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(v_PagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_PagoLayout.createSequentialGroup()
                    .addGap(0, 211, Short.MAX_VALUE)
                    .addComponent(p_mosFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(v_PagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_PagoLayout.createSequentialGroup()
                    .addContainerGap(221, Short.MAX_VALUE)
                    .addComponent(p_capEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(v_PagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_PagoLayout.createSequentialGroup()
                    .addContainerGap(219, Short.MAX_VALUE)
                    .addComponent(p_corteCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        v_PagoLayout.setVerticalGroup(
            v_PagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p_ingFac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(v_PagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(p_capIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(v_PagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(p_mosFac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(v_PagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(p_capEgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(v_PagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(p_corteCaja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(v_Pago, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ing_FacturaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ing_FacturaBtnActionPerformed
                
        p_ingFac.setVisible(true);
        p_capIngreso.setVisible(false);
        p_mosFac.setVisible(false);
        p_capEgreso.setVisible(false);
        p_corteCaja.setVisible(false);
        
    }//GEN-LAST:event_ing_FacturaBtnActionPerformed

    private void volver_MenuPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_MenuPBtnActionPerformed
        menu_Principal mainMenu = new menu_Principal();
        mainMenu.setSize(720, 472);
        mainMenu.setLocation(0,0);

        v_Pago.removeAll();
        v_Pago.add(mainMenu, BorderLayout.CENTER);
        v_Pago.revalidate();
        v_Pago.repaint();
        
        
        
    }//GEN-LAST:event_volver_MenuPBtnActionPerformed

    private void ver_FacturaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_FacturaBtnActionPerformed
        p_ingFac.setVisible(false);
        p_capIngreso.setVisible(false);
        p_mosFac.setVisible(true);
        p_capEgreso.setVisible(false);
        p_corteCaja.setVisible(false);
    }//GEN-LAST:event_ver_FacturaBtnActionPerformed

    private void add_IngresoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_IngresoBtnActionPerformed
        p_ingFac.setVisible(false);
        p_capIngreso.setVisible(true);
        p_mosFac.setVisible(false);
        p_capEgreso.setVisible(false);
        p_corteCaja.setVisible(false);
    }//GEN-LAST:event_add_IngresoBtnActionPerformed

    private void add_EgresoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_EgresoBtnActionPerformed
        p_ingFac.setVisible(false);
        p_capIngreso.setVisible(false);
        p_mosFac.setVisible(false);
        p_capEgreso.setVisible(true);
        p_corteCaja.setVisible(false);
    }//GEN-LAST:event_add_EgresoBtnActionPerformed


    
    private void ver_CorteCajaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_CorteCajaBtnActionPerformed
        p_ingFac.setVisible(false);
        p_capIngreso.setVisible(false);
        p_mosFac.setVisible(false);
        p_capEgreso.setVisible(false);
        p_corteCaja.setVisible(true);
        
        verIngTxt.setText(ingresoTxt.getText());
        verEgrTxt.setText(egresoTxt.getText());
        
        verCorte.setText(String.valueOf(caja.getIngresos() - caja.getEgresos()));    
        
    }//GEN-LAST:event_ver_CorteCajaBtnActionPerformed

    private void ver_FacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_FacActionPerformed
         
        if (veri_IdTxt.getText().equals(idTxt.getText())) {
            idLabel.setVisible(true);
            montoLabel.setVisible(true);
            descLabel.setVisible(true);
            ver_IdFacTxt.setVisible(true);
            ver_MontoTxt.setVisible(true);
            ver_DescTxt.setVisible(true);
            ver_IdFacTxt.setText(idTxt.getText());
            ver_MontoTxt.setText(montoTxt.getText());
            ver_DescTxt.setText(descTxt.getText());
        }else{
            JOptionPane.showMessageDialog(null, "ID Incorrecto, favor de ingresar de nuevo");   
        }
    }//GEN-LAST:event_ver_FacActionPerformed

    private void montoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoTxtActionPerformed

    private void salvar_FacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_FacActionPerformed
        // TODO add your handling code here:
        factura01.setDescripcion(descTxt.getText());
        if (!factura01.setMonto(montoTxt.getText())){
            JOptionPane.showMessageDialog(null, "Favor de ingresar un monto con decimal");
        }else if(!factura01.setId_Fac(idTxt.getText())){
            JOptionPane.showMessageDialog(null, "Favor de ingresar un ID de 5 dígitos");
        }
        if (factura01.validacion(idTxt.getText())) {
               try{
                Connection con = getConnection();
            String Cadena = "INSERT INTO facturas(monto, id_Fac) VALUES ('"+factura01.getMonto()+"', '"+factura01.getId_Fac()+"');";            
                PreparedStatement posted = con.prepareStatement(Cadena);
                posted.executeUpdate();
                //return true;
            } catch(Exception e){
                System.out.println(e);
                //return false;
            }
            JOptionPane.showMessageDialog(null, "Factura ingresada exitosamente");
        }
    }//GEN-LAST:event_salvar_FacActionPerformed

    private void veri_IdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veri_IdTxtActionPerformed

    }//GEN-LAST:event_veri_IdTxtActionPerformed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void ver_IdFacTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_IdFacTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ver_IdFacTxtActionPerformed

    private void ver_MontoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_MontoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ver_MontoTxtActionPerformed

    private void ver_DescTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_DescTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ver_DescTxtActionPerformed

    private void salvar_IngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_IngActionPerformed
        if (!caja.setIngresos(ingresoTxt.getText())) {
            JOptionPane.showMessageDialog(null, "Favor de ingresar un monto");
        }else {
            JOptionPane.showMessageDialog(null, "Monto guardado exitosamente");
        }
    }//GEN-LAST:event_salvar_IngActionPerformed

    private void ingresoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoTxtActionPerformed

    private void salvar_EgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_EgrActionPerformed
            // TODO add your handling code here:
        if (!caja.setEgresos(egresoTxt.getText())) {
            JOptionPane.showMessageDialog(null, "Favor de ingresar un monto");
        }else{
            JOptionPane.showMessageDialog(null, "Monto guardado exitosamente");
        }
    }//GEN-LAST:event_salvar_EgrActionPerformed

    private void verEgrTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEgrTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verEgrTxtActionPerformed

    private void verIngTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verIngTxtActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_verIngTxtActionPerformed

    private void verCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCorteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verCorteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_EgresoBtn;
    private javax.swing.JButton add_IngresoBtn;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextField descTxt;
    private javax.swing.JTextField egresoTxt;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton ing_FacturaBtn;
    private javax.swing.JTextField ingresoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel montoLabel;
    private javax.swing.JTextField montoTxt;
    private javax.swing.JPanel p_Btn;
    private javax.swing.JPanel p_capEgreso;
    private javax.swing.JPanel p_capIngreso;
    private javax.swing.JPanel p_corteCaja;
    private javax.swing.JPanel p_ingFac;
    private javax.swing.JPanel p_mosFac;
    private javax.swing.JButton salvar_Egr;
    private javax.swing.JButton salvar_Fac;
    private javax.swing.JButton salvar_Ing;
    private javax.swing.JPanel v_Pago;
    private javax.swing.JTextField verCorte;
    private javax.swing.JTextField verEgrTxt;
    private javax.swing.JTextField verIngTxt;
    private javax.swing.JButton ver_CorteCajaBtn;
    private javax.swing.JTextField ver_DescTxt;
    private javax.swing.JButton ver_Fac;
    private javax.swing.JButton ver_FacturaBtn;
    private javax.swing.JTextField ver_IdFacTxt;
    private javax.swing.JTextField ver_MontoTxt;
    private javax.swing.JTextField veri_IdTxt;
    private javax.swing.JButton volver_MenuPBtn;
    // End of variables declaration//GEN-END:variables
}
